"""add embeddings table

Revision ID: 4fd50ef2630a
Revises: f14b01c3e80c
Create Date: 2026-04-06 06:44:22.598699

"""

import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import HALFVEC
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4fd50ef2630a"
down_revision: Union[str, Sequence[str], None] = "f14b01c3e80c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Read embedding dimensions from the environment so the migration
# adapts to whatever model the deployer has configured.
_EMBEDDING_DIM = int(os.environ.get("FASTAI_EMBEDDING_DIMENSIONS", "1536"))


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("embedding", HALFVEC(_EMBEDDING_DIM), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column(
            "chunk_index",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.Column("token_count", sa.SmallInteger(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_type",
            "source_id",
            "chunk_index",
            "embedding_model",
            name="uq_embeddings_source_chunk_model",
        ),
    )
    op.create_index(
        "ix_embeddings_halfvec_hnsw",
        "embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_index(
        "ix_embeddings_source", "embeddings", ["source_type", "source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_embeddings_source", table_name="embeddings")
    op.drop_index(
        "ix_embeddings_halfvec_hnsw",
        table_name="embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_table("embeddings")
    # ### end Alembic commands ###
